### ISSUE TITLE
It would be really helpful to start with explaining np.any() and np.all() for the lab

### ISSUE THREAD

**Issue by twood2015** [learn-co-curriculum/dsc-intro-to-probability-lab#5]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ x] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

It would be helpful to include an explanation of np.any() or np.all() for the lab, unless if it was the intention
to make us look it up in documentation. A lot of the instructions in this lab felt kind of vague and didn't
give a good sense of what the overall direction was for the calculations we were trying to perform.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
This lab is no longer part of the curriculum as of v3.0. So while it is a good suggestion, it is not necessary.
