### ISSUE TITLE
.sum placemente

### ISSUE THREAD

**Issue by rafvrab** [learn-co-curriculum/dsc-intro-to-probability-lab#6]
## Link to Canvas

I spotted an error on the "Solutions" page:
https://github.com/learn-co-curriculum/dsc-intro-to-probability-lab/tree/solution

## Issue Subtype

- [ ] Master branch code
- [x ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
ON 
"Some more practice on the sample and event spaces"
c. What is the probability of the outcome having a sum of exactly 8?

It says:

sum_dice = np.sum(sample_dice, axis = 1)
sum_8 = sum(sum_dice == 8)

It should say:

sum_dice = np.sum(sample_dice, axis=1)
sum_8 = (sum_dice == 8).sum()

The way it appears in the "Solutions" page does not produce the desired answer.
```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
thanks for opening this issue :wave: both the answer on the solution branch, the solution you provided, and using `np.sum()` are correct ways to calculate the same value. 

``` python
(sum_dice==8).sum() == sum(sum_dice==8) == np.sum(sum_dice==8)
```

I am closing this issue at this time.
